
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 17 08:10:45 CEST 2013
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 46;
  public static final int CONST = 3;
  public static final int EQUALS = 28;
  public static final int LPAREN = 39;
  public static final int SEMI = 38;
  public static final int GREATER = 32;
  public static final int LESS = 30;
  public static final int MINUS = 18;
  public static final int RPAREN = 40;
  public static final int AND = 24;
  public static final int OR = 25;
  public static final int BOOL = 47;
  public static final int COMMA = 41;
  public static final int CLASS = 4;
  public static final int INC = 22;
  public static final int DIV = 20;
  public static final int PLUS = 17;
  public static final int GREATER_EQUALS = 33;
  public static final int IF = 11;
  public static final int THIS = 9;
  public static final int DOT = 42;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int EQUAL = 16;
  public static final int SUPER = 10;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 19;
  public static final int NUMBER = 43;
  public static final int MOD = 21;
  public static final int IDENT = 44;
  public static final int BREAK = 15;
  public static final int VOID = 7;
  public static final int LBRACK = 36;
  public static final int LBRACE = 34;
  public static final int ELSE = 12;
  public static final int LESS_EQUALS = 31;
  public static final int RBRACK = 37;
  public static final int READ = 27;
  public static final int WHILE = 13;
  public static final int NOT_EQUALS = 29;
  public static final int RBRACE = 35;
  public static final int EXTENDS = 5;
  public static final int PROG = 2;
  public static final int STRING = 45;
  public static final int DEC = 23;
  public static final int PRINT = 26;
  public static final int DO = 14;
}

